### ISSUE TITLE
DAQC2 fails to getADC

### ISSUE THREAD

**Issue by dudleyjosh** [mharsch/node-pi-plates#3]
From the code snippet and error below... it appears to be an issue with the BASEplate.js? I first discovered this issue when trying to run a Node-RED flow I had working months ago with the node-red-contrib-pi-plates node reading an ADC channel on the DAQC2 plate.

```
// Test changing voltage on DAC0 by monitoring on ADC0
// assumes that analog input 0 is connected to analog output 0
// on a DAQC2 set to address 0 via jumpers

const DAQC2plate = require('../DAQC2plate');

DP0 = new DAQC2plate(0);

const obj = {args: {}};
let i = 0;
setInterval( () => {
    if (i > 4.097)
        i = 0;
    obj.cmd = "setDAC"
    obj.args.channel = 0;
    obj.args.value = i;
    DP0.send(obj, (reply) => {
        DP0.send({cmd: "getADC", args: {channel: 0}}, (reply) => {
            console.log('voltage is ' + reply.voltage);
        });
    });
    i += 0.5;
}, 1000);
```

```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at WorkQueue.do_cmd [as worker] (/home/pi/pi-plates/node_modules/pi-plates/BASEplate.js:26:17)
    at Immediate.<anonymous> (/home/pi/pi-plates/node_modules/vasync/lib/vasync.js:562:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
    at writeOrBuffer (_stream_writable.js:399:5)
    [... lines matching original stack trace ...]
    at tryOnImmediate (timers.js:676:5)
```

**Comment by mharsch** [comment]
first guess would be that the underlying (python) child process is failing to start.  The most common cause would be python isn't installed, or a python2/python3 mismatch. Are there other errors in the nodered log from the time nodered started?

**Comment by dudleyjosh** [comment]
I fired up python on the Raspberry Pi and I was able to use getADC() just fine that way?

```
$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import piplates.DAQC2plate as DAQ2
>>> DAQ2.getADC(0,0)
2.505
>>> DAQ2.getADC(0,0)
2.505
```

Below is what I get from Node-RED when it fails...

```
8 Apr 12:36:57 - [red] Uncaught Exception:
8 Apr 12:36:57 - Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at WorkQueue.do_cmd (/home/pi/.node-red/node_modules/pi-plates/BASEplate.js:26:17)
    at Immediate.<anonymous> (/home/pi/.node-red/node_modules/vasync/lib/vasync.js:562:6)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by dudleyjosh** [comment]
I do see that Node-RED shows this error too on startup...

```
stderr: Traceback (most recent call last):
  File "/home/pi/.node-red/node_modules/pi-plates/plate_io.py", line 7, in <module>
    import piplates.THERMOplate as TP
ImportError: No module named THERMOplate
```

**Comment by dudleyjosh** [comment]
Well, after poking around and messing with it a bit, I decided to force a reinstall of the pi-plates python modules... and that seems to have fixed things... not exactly sure what the issue was?

`$ pip install --upgrade --force-reinstall pi-plates`

**Comment by mharsch** [comment]
Note for future reference: we're going to python3-only support for this module.  As of this writing, the current version of the pi-plates python (pip3) package is 2.6 and the required Raspberry Pi OS packages are:
python3-pip
python3-spidev
python3-rpi.gpio
python3-pygame
